### ISSUE TITLE
WHAT IS THE $file in php?

### ISSUE THREAD

**Issue by Kulaxyz** [sasan-salem/DummyBytes#1]

**Comment by sasan-salem** [comment]
The **`$file`** is empty because it's a fake PDF file.

**Comment by sasan-salem** [comment]
The **`$file`** is empty because it's a fake PDF file. It does not matter what. Maybe it was better to I use a **`'blabla'`** instead of a **`$file`** for simplicity.

**Comment by Kulaxyz** [comment]
> The **`$file`** is empty because it's a fake PDF file. It does not matter what. Maybe it was better to I use a **`'blabla'`** instead of a **`$file`** for simplicity.

Thanks, now its clear
