### ISSUE TITLE
Website Issue 

### ISSUE THREAD

**Issue by gangapurambhargav** [sasan-salem/DummyBytes#2]
My website is not opening in chrome instead saying my website.com

**Comment by sasan-salem** [comment]
What is your OS and default browser?

**Comment by gangapurambhargav** [comment]
Android 10,chrome.

**Comment by sasan-salem** [comment]
It's needs to be debugged. I haven't enough data and I don't know where is your problem. Did you deployed you website to I check that?

**Comment by gangapurambhargav** [comment]
Its a basic Portfolio website i built with html,css in github pages here is the link :-https://gangapurambhargav.github.io/bio/links.html

**Comment by sasan-salem** [comment]
have you implemented DummyBytes API in your back-end? you should implement that like [DummyBytes in php](https://github.com/sasan-salem/DummyBytes/blob/master/PHP/DummyBytes.php) and in your Javascript code, you should add your API link. According to your code, I think you haven't that API in your server.

**Comment by gangapurambhargav** [comment]
https://github.com/gangapurambhargav/bio
You can check

**Comment by sasan-salem** [comment]
I saw your code. you just copied the code and didn't change the URLs to your website and API.
